// <auto-generated />

using Medicos.Backend.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Medicos.Backend.Migrations
{
    [DbContext(typeof(TestingContext))]
    [Migration("20260202143359_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Medicos.Backend.Data.Models.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Especialidad", (string)null);
                });

            modelBuilder.Entity("Medicos.Backend.Data.Models.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Especialidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Especialidad");

                    b.ToTable("Medico", (string)null);
                });

            modelBuilder.Entity("Medicos.Backend.Data.Models.Medico", b =>
                {
                    b.HasOne("Medicos.Backend.Data.Models.Especialidad", "EspecialidadNavigation")
                        .WithMany("Medicos")
                        .HasForeignKey("Especialidad")
                        .IsRequired();

                    b.Navigation("EspecialidadNavigation");
                });

            modelBuilder.Entity("Medicos.Backend.Data.Models.Especialidad", b =>
                {
                    b.Navigation("Medicos");
                });
#pragma warning restore 612, 618
        }
    }
}
